### PR TITLE
Add a mac icon

### PR DESCRIPTION
**Pull request by benogle**
Adds a mac icon. 

screen shot 2015-08-01 at 1 01 07 pm

This icon has been lifted from the internal flask prototype app. @probablycorey, is this ok?

@kevinsawicki This is adding more platform (err darwin) specific junk, which you are way more versed in. I'd like to keep much of the logic for that kind of thing out of this repo, and push the onus onto modules like electron-packager, or something else that wraps the packager like a CLI.

### CODE REVIEW

**Comment by simurai** [comment]
Is the idea to have a different Mac icon so that it doesn't conflict with the electron icon? So the electron icon would only be used on the website, stickers etc. but not as the default app icon that people would have to replace? Maybe then all app icons should be different, not just for Mac.

**Comment by benogle** [comment]
Yeah, I would like to have a sample icon that shows basically what it takes to get your icon into the app. Definitely would be nice to have an icon for all platforms in this.

**Comment by simurai** [comment]
Could be something like:

screen shot 2015-08-04 at 10 37 24 am

Same icon, just different shape for each platform.

@benogle Do you have the original source file?

**Comment by benogle** [comment]
Ok, cant use this one. Apparently it was Something From The Internet. Closing.

**Pull request closed without merging**
